// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	MEMORY_KV: KVNamespace;
	CRON_SCHEDULE: "0 12 * * *";
	AGENT_SYSTEM_PROMPT: "You are an assistant that helps orchestrate a smart home by coordinating Cloudflare Worker resources with Home Assistant.";
	VISION_MODEL: "@cf/unum/uform-gen2-qwen-500m";
	CHAT_MODEL: "@cf/meta/llama-3-8b-instruct";
	HA_WEBSOCKET_DO: DurableObjectNamespace<import("./src/index").HAWebsocketDurableObject>;
	RECORDER_DB: D1Database;
	CONFIG_DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
}
